name: Fetch BMKG Earthquake Data

on:
  schedule:
    - cron: "0 * * * *"  # Setiap 1 jam
  workflow_dispatch:  # Bisa dijalankan manual juga

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch BMKG Earthquake Data
        run: python fetch_bmkg.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add bmkg_earthquake_data.csv
          git commit -m "update: new earthquake data $(date)" || echo "no changes"
          git push
